import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/layouts/Navbar";

const camood = localFont({
  src: "../public/fonts/camood.otf",
  variable: "--font-camood",
});

const urbanist = localFont({
  src: "../public/fonts/urbanist.ttf",
  variable: "--font-urbanist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(urbanist.variable, camood.variable, "antialiased")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}