import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { InvoiceProvider } from "@/components/providers/InvoiceProvider";

const alphabet = localFont({
  src: "../public/fonts/Alphabet.otf",
  variable: "--font-alphabet",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alphabet.variable} antialiased`}
        suppressHydrationWarning
      >
        <InvoiceProvider>
          {children}
        </InvoiceProvider>
      </body>
    </html>
  );
}